### ISSUE TITLE
NO LAUNCH FILE PROVIDED +  POOR DOCUMENTATION

### ISSUE THREAD

**Issue by leocorp96** [ROS-Aceinna/ros_openimu#2]
Hello I am trying to get this package to run but it seems the attached Application Note file doesn't reflect the content on this repo. First there's no launch provided. And there's little or no documentation at all as to what parameters are needed to run the python file.

**Comment by GilenTell** [comment]
Hi,
It's true that there isn't any ros launch file and that the application note does not make any sense yet.
But there is a way to test the ros driver. Run like this:
`rosrun ros_openimu openimu_driver.py`

I have debugged some bugs that I pointed out in the previous issue. https://github.com/ROS-Aceinna/ros_openimu/issues/1

The driver finds autonomously the Aceinna device, so you have not to pass any parameter in the first test. I have tested this with an openIMU300ZI. The magnetometer topic is not working, but the accelerometer is reporting data.

This is a beta version and we will have to wait for Aceinna's colleagues to debug and release it.

Bye,
Guillermo

**Comment by leocorp96** [comment]
Hi @GilenTell ,

Thanks for the insight and quick response. I have the  openIMU300RI which arrived yesterday but even though it gets detected by running the "openimu_driver.py" the call to read IMU data seems to return "None" which causes the program to terminate unexpectedly. My question is, do I have to program(st-link way) the sensor before I can data from it??

**Comment by ROS-Aceinna** [comment]
Hi Leocorp96, we have updated the repo with a launch file and also the app note to reflect the changes made. 

The default RS232 rate for the Openimu300RI is 0 when shipped from the factory. You will have to set this to a higher value (like 100Hz) for use with the ros driver. We will add the capability to set parameters in a future update to this repository.
At the moment you can set the packet rate and save permanently with the standard evaluation software.

1. Download and run the server .exe at [https://developers.aceinna.com/devices/connect](url)
2. With the device connected and server running click the devices->openimu tab
3. click settings, change the packet rate and save permanently (otherwise change will be lost after a power cycle)
4. There is a video on our YouTube site with further information - skip to 39:30 for changing settings [https://www.youtube.com/watch?v=szHDnQdDAXw](url)

**Comment by leocorp96** [comment]
> Hi Leocorp96, we have updated the repo with a launch file and also the app note to reflect the changes made.
> 
> The default RS232 rate for the Openimu300RI is 0 when shipped from the factory. You will have to set this to a higher value (like 100Hz) for use with the ros driver. We will add the capability to set parameters in a future update to this repository.
> At the moment you can set the packet rate and save permanently with the standard evaluation software.
> 
> 1. Download and run the server .exe at [https://developers.aceinna.com/devices/connect](url)
> 2. With the device connected and server running click the devices->openimu tab
> 3. click settings, change the packet rate and save permanently (otherwise change will be lost after a power cycle)
> 4. There is a video on our YouTube site with further information - skip to 39:30 for changing settings [https://www.youtube.com/watch?v=szHDnQdDAXw](url)

Hello @ROS-Aceinna, I followed the outlined instructions "Save Permanently": I get the message "Saved successfully" but then it keeps resetting to 0 on power cycle. My software version is "IMU_J1939 03.00".
**QUICK FIX: Is there a way to configure this variable on each connection?**

**Comment by ROS-Aceinna** [comment]
Hi Leocorp96, if you update the app on the openimu to the attached you should be able to save permanently. To do this go to [https://developers.aceinna.com/code/upload](url) and unzip and then add the attached application (openimu300Ri IMU app with packet rate of 100Hz). You can then write it to the part.

[OpenIMU300RI app.zip](https://github.com/ROS-Aceinna/ros_openimu/files/6265032/OpenIMU300RI.app.zip)

**Comment by leocorp96** [comment]
Works perfect. Thanks for taking the time @ROS-Aceinna
